[stable-v2.10] drivers: dma: intel_adsp_hda: change L1 exit defaults
thesofproject/zephyr pull request #79
Opened 2024-06-19 18:36 UTC by kv2019i

DMA_INTEL_ADSP_HDA_TIMING_L1_EXIT should be set by default for both Intel ACE15 and ACE20 platforms.

Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>
(cherry picked from commit a4fdd915d5350f27afe6b3435d248075eb86dc49)

2024-06-19 18:41 UTC, abonislawski approved these changes

2024-06-19 19:57 UTC, marc-hb approved these changes

2024-06-19 20:02 UTC, marc-hb requested changes
Wait: https://github.com/thesofproject/zephyr/commit/a4fdd915d5350f27afe6b3435d248075eb86dc49

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.


Considering how convoluted this L1 situation has been[*], the commit message definitely deserves the correct SHA1


[*] https://github.com/thesofproject/sof/pull/9194 etc.

2024-06-20 07:42 UTC, kv2019i commented
@marc-hb the SHA1 is the correct one merged to upstream Zephyr:
- https://github.com/thesofproject/zephyr/commit/a4fdd915d5350f27afe6b3435d248075eb86dc49
- https://github.com/zephyrproject-rtos/zephyr/commit/a4fdd915d5350f27afe6b3435d248075eb86dc49

The warning was emitted as nobody had pushed Zephyr main to the SOF fork project. I now did that to silence the warning.

Ok to merge?

2024-06-20 08:12 UTC, kv2019i commented
I've double/triple checked this now, so @marc-hb I'll take the risk and ignore your -1 so I can proceed with rc1 preps during my workday today.

2024-06-20 08:13 UTC, merged